[build]
builder = "nixpacks"
nixpacksVersion = "1.38.0"

[variables]
NIXPACKS_NODE_VERSION = "22"

[deploy]
startCommand = "npm run build && npm start"
healthcheckPath = "/health"
restartPolicyType = "ON_FAILURE"
